---
# prefix_equivalents.yaml
"DICTYBASE": "dictyBase"
"DO:DOID": "DOID"
"Ensembl": "ENSEMBL"
"ENSEMBL GENE": "ENSEMBL"
"Entrez-Gene": "NCBIGene"
"Entrez.Gene": "NCBIGene"
"EntrezGene": "NCBIGene"
"ENTREZ_GENE": "NCBIGene"
"Entrez": "NCBIGene"
"FB": "FlyBase"
"FLYBASE": "FlyBase"
"GENBANK_GENOMIC_DNA_ACCESSION": "NCBIGenome"
"GENBANK_PROTEIN_ACCESSION": "NCBIProtein"
"GOC": "GO_REF"
"HGNC:HGNC": "HGNC"
"HPO": "HP"
"MGI:MGI": "MGI"
"MIM": "OMIM"
"MIRBASE": "miRBase"
"NCBI-Gene": "NCBIGene"
"NCBI.Gene": "NCBIGene"
"ORDO": "ORPHA"
"Orphanet": "ORPHA"
"Orpha": "ORPHA"
"PubMed": "PMID"
"Reactome": "REACT"
"TREMBL": "TrEMBL"
"UNIPROT-ISOFORM": "UniProtKB"
"UNIPROT_PRO": "UniProtKB"
"VGNC:VGNC": "VGNC"
"WB_REF": "WormBase"
"WB": "WormBase"
"WORMBASE-OLD": "WormBase"
"WORMBASE": "WormBase"
