[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "bioweave"
author = "The Monarch Initiative"
author-email = "info@monarchinitiative.org"
home-page = "https://github.com/kshefchek/bioweave"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Operating System :: POSIX :: Linux",
]
requires = [
    "pydantic >=1.0.0,<2.0.0",
    "pyyaml >=5.3.1,<6.0.0",
    "requests >=2.24.0,<3.0.0",
    "typer >=0.3",
]
description-file = "README.md"
requires-python = ">=3.6"

[tool.flit.metadata.urls]
Documentation = "https://github.com/kshefchek/bioweave"

[tool.flit.metadata.requires-extra]
test = [
    "pytest >=6.0.0",
]
doc = [
    "mkdocs >=1.1.2,<2.0.0",
]
dev = [
    "autoflake >=1.3.1,<2.0.0",
    "flake8 >=3.8.3,<4.0.0",
    "black ==20.8b1",
    "isort >=5.0.6,<6.0.0",
]

[tool.flit.scripts]
bioweave = "bioweave:main"

[tool.black]
line_length = 120
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true

# https://koxudaxi.github.io/pydantic-pycharm-plugin/type-checker-for-pydantic/
[tool.pydantic-pycharm-plugin]
# You can select higlith level  from "warning",  "weak_warning", "disable"
acceptable-type-highlight = "disable"

[tool.pydantic-pycharm-plugin.acceptable-types]
"bioweave.model.curie.Curie" = ["str"]
