name: 'stringdb'

dataset_description:
  ingest_title: 'String DB'
  ingest_url: 'String'
  data_rights: 'String'

local_dir: './string'

source_templates:
  - 'protein-links-detailed'

map_templates:
  - 'entrez-2-string'