name: 'protein-links-detailed'

data_dir: 'todo'

file_metadata:
  license: "this file has a unique license"

depends_on:
  - 'entrez_2_string'

on_map_failure: 'warning'

delimeter: 'tab'
header_delimeter: 'tab'

compression: 'gzip'

skip_lines: 0

files:
  - '9606.protein.links.detailed.v11.0.txt.gz'
  - '10090.protein.links.detailed.v11.0.txt.gz'

fields:
  - 'protein1'
  - 'protein2'
  - 'neighborhood'
  - 'fusion'
  - 'cooccurence'
  - 'coexpression'
  - 'experimental'
  - 'database'
  - 'textmining'
  - 'combined_score{int}'

filter_out:
  'combined_score':
     filter: 'lt'
     value: 700

associations:
  - 'PairwiseGeneToGeneInteraction'

column_mappings:
  - 'protein1': 'Gene'
  - 'protein2': 'Gene'
