name: 'protein-links-detailed'

local_dir: 'todo'

file_metadata:
  license: "this file has a unique license"

depends_on:
  - 'entrez_2_string'

delimeter: 'tab'
header_delimeter: 'tab'

compression: 'gzip'

skip_lines: 0

files:
  - '9606.protein.links.detailed.v11.0.txt.gz'
  - '10090.protein.links.detailed.v11.0.txt.gz'

columns:
  - 'protein1'
  - 'protein2'
  - 'neighborhood'
  - 'fusion'
  - 'cooccurence'
  - 'coexpression'
  - 'experimental'
  - 'database'
  - 'textmining'
  - 'combined_score{int}'

filter_row:
  'combined_score':
    - 'gte'
    - 700

associations:
  - 'PairwiseGeneToGeneInteraction'

max_associations_per_line: 1

column_mappings:
  - 'protein1': 'Gene'
  - 'protein2': 'Gene'
