name: protein-links-detailed

file_metadata:
  license: "this file has a unique license"

ingest_type: 'primary'

depends_on:
  - entrez_2_string

delimeter: 'tab'
header_delimeter: 'tab'

files:
  - '9606.protein.links.detailed.v11.0.txt.gz'
  - '10090.protein.links.detailed.v11.0.txt.gz'

columns:
  - 'protein1'
  - 'protein2'
  - 'neighborhood'
  - 'fusion'
  - 'cooccurence'
  - 'coexpression'
  - 'experimental'
  - 'database'
  - 'textmining'
  - 'combined_score'

filter_row:
  'combined_score':
    - 'gte'
    - '700'

associations:
  - PairwiseGeneToGeneInteraction

max_associations_per_line: 1

column_mappings:
  - 'protein1': 'Gene'
  - 'protein2': 'Gene'
