name: 'Monarch Ingest'
biolink_version: '1.03'

# Archive version?

output: ./out/

curie_map: /foo/bar/baz

sources:
  - foo
  - bar
  - baz

serializations:
  - nturtles
  - jsonlines
  - tsv
  - rdfstar

cache_maps: true
