name: 'Monarch Ingest'
biolink_version: '1.03'
logfile: '/path/to/log'

# Archive version?

curie_map: /foo/bar/baz

sources:
  - foo
  - bar
  - baz

serializations:
  - nturtles
  - jsonlines
  - tsv
  - rdfstar
