name: 'morbidmap'

file_metadata:
  license: "https://www.omim.org/downloads"

depends_on:
  - 'mim2gene'
  - 'mimtitles'
  -
on_map_failure: 'error'

delimeter: 'tab'
header_delimeter: 'tab'

skip_lines: 4

files:
  - 'morbidmap.txt'

fields:
  - 'Phenotype'
  - 'Gene Symbols'
  - 'MIM Number'
  - 'Cyto Location'

associations:
  - 'GeneToDiseaseAssociation'

column_mappings:
  - 'Phenotype': 'Disease'
  - 'MIM Number': 'Gene'
