# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-ubuntu-latest:
    name: test py${{ matrix.python-version }} on linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']
    env:
      PYTHON: ${{ matrix.python-version }}
      OS: ubuntu

    steps:
      - uses: actions/checkout@v2

      - name: make test
        run: make test
